// Deterministic Vitest source from validated case records. Model text only ever
// appears inside JSON-escaped string literals or sanitized line comments.
import { CaseRecord } from '../core/types';
import { assertJson } from './validate';

/** A string literal safe to embed in TypeScript source. */
const lit = (s: string) => JSON.stringify(s).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');

/** Text safe inside a `//` comment: one line, no control characters. */
export const commentText = (s: string, max = 160) =>
  s
    .replace(/[\u0000-\u001f\u007f\u2028\u2029]/g, ' ')
    .replace(/\*\//g, '* /')
    .slice(0, max);

/** A JSON value rebuilt at runtime from a string literal (fresh copy per call). */
const data = (v: unknown) => {
  assertJson(v as never);
  return `data(${lit(JSON.stringify(v))})`;
};

export const FINGERPRINT_TAG = 'testforge-fingerprint:';

export function renderTests(opts: { runId: string; exportName: string; importPath: string; cases: CaseRecord[]; demo: boolean }): string {
  const { exportName } = opts;
  if (!/^[A-Za-z_$][\w$]*$/.test(exportName)) throw new Error('invalid export name');
  const lines = [
    `// Generated by TestForge (run ${opts.runId})${opts.demo ? ' in DEMO mode with a fake model' : ''}.`,
    '// Ordinary Vitest tests: edit or delete freely. Inputs are called with Reflect.apply,',
    '// so they exercise runtime behavior, not compile-time argument types.',
    "import { test, expect } from 'vitest';",
    `import { ${exportName} } from ${lit(opts.importPath)};`,
    '',
    'const data = (json: string): unknown => JSON.parse(json);',
    '',
  ];
  for (const c of opts.cases) {
    const ev = c.evidence.map((e) => `${e.fileId}:${e.startLine}-${e.endLine}`).join(', ') || 'none';
    lines.push(`// ${c.id} | ${c.category} | basis: ${c.basis} | evidence: ${commentText(ev, 80)}`);
    lines.push(`// ${FINGERPRINT_TAG} ${c.fingerprint}`);
    if (c.rationale) lines.push(`// ${commentText(c.rationale)}`);
    lines.push(`test(${lit(`[${c.id}] ${c.title}`)}, () => {`);
    lines.push(`  const args = ${data(c.args)} as unknown[];`);
    if (c.expectation.kind === 'returns') {
      lines.push(`  expect(Reflect.apply(${exportName}, undefined, args)).toStrictEqual(${data(c.expectation.value)});`);
    } else {
      lines.push('  let thrown: unknown;');
      lines.push('  let threw = false;');
      lines.push(`  try {\n    Reflect.apply(${exportName}, undefined, args);\n  } catch (error) {\n    threw = true;\n    thrown = error;\n  }`);
      lines.push('  expect(threw).toBe(true);');
      if (c.expectation.errorName !== undefined) lines.push(`  expect((thrown as Error).name).toBe(${lit(c.expectation.errorName)});`);
      if (c.expectation.messageIncludes !== undefined) lines.push(`  expect(String((thrown as Error).message)).toContain(${lit(c.expectation.messageIncludes)});`);
    }
    lines.push('});', '');
  }
  return lines.join('\n');
}

/** Fingerprints recorded in previously applied TestForge files. */
export function readFingerprints(text: string): string[] {
  return [...text.matchAll(/testforge-fingerprint: ([0-9a-f]{16})/g)].map((m) => m[1]);
}
